- src: https://github.com/DeusDimitrius/ANSIBLE_DOCKER_ROLE.git
  path: roles/
  name: docker-role
- src: https://github.com/DeusDimitrius/ANSIBLE_WEB_APP_ROLE.git
  path: roles/
  name: flask-role
- src: https://github.com/DeusDimitrius/ANSIBLE_NGINX_ROLE.git
  path: roles/
  name: nginx-role
