---
#
#- src: https://github.com/DeusDimitrius/ANSIBLE_DOCKER_ROLE.git
#  name: ANSIBLE_DOCKER_ROLE
#- src: https://github.com/DeusDimitrius/ANSIBLE_WEB_APP_ROLE.git
#  name: flask-role
#- src: https://github.com/DeusDimitrius/ANSIBLE_NGINX_ROLE.git
#  name: nginx-role

# with tag
- hosts: local
  remote_user: root
  roles:
  - ANSIBLE_DOCKER_ROLE
  - flask-role
  - nginx-role
